### PR TITLE
feat: profile page

### PR DESCRIPTION
**Pull request by rohanmathur91**
## Description:
- Added profile page for the user.
- From anyone's profile, the currently logged-in user can follow or unfollow their following and follower users.
- Fix a few modal and profile page layout issues.

## Link:
https://deploy-preview-6--evolt-myspace.netlify.app

## Screenshot (GIF):
chrome-capture (15)

### CODE REVIEW

**Review by ishitakeshawani — APPROVED** [review]
UI looks good
Everything working fine
Looks good to me

**Review by yashpatel1797 — APPROVED** [review]
code looks clean
file structure is good
design looks consistent

**Comment by pruthvirajmv** [comment]
Hey Rohan,
Great work in terms of UI & code. 
Redux implementation is also good

A couple of things would really like you do is adding a favicon & updating the App title
Sorry for commenting bit late!

**Comment by rohanmathur91** [comment]
> 

Thanks, @pruthvirajmv
I will update the same.

**Pull request merged**
